apiVersion: v2

# For name, it should be <template-slug-here> because most of the Kubernetes
# deployment guides we wrote usually used the alias 'cdrs-deploy' for our
# Helm Charts repo. The upstream repo (cdr/code-server) is excluded from that rule.
name: starter-pack
# For description, update this to tell users what to included in your chart.
description: A Helm chart for deploying code-server, with all the essientials like Cloudflare Tunnel and croc.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# TL;DR: Check the base Docker image in the root Dockerfile and update this version
appVersion: 3.10.2

# List of Helm Charts maintainers, this is requored for human reviews to get passed
# before being merged to our Helm Charts repo on GitHub Pages.
maintainers:
  - name: 'Andrei Jiroh Halili' # Your screen name on GitHub or legal name
    email: 'andreijiroh@madebythepins.tk' # Your email address you generally used for commits
    url: 'https://github.com/AndreiJirohHaliliDev2006' # GitHub profile

keywords:
  - starter-pack
  # Comment out this one below if you ever forked me instead of using
  # the repo generator tool.
  - github-repo-templates

# Homepage and sources should be your repo's URL.
home: "https://github.com/code-server-boilerplates/starter-pack"
sources:
  - https://github.com/code-server-boilerplates/starter-pack
  # Don't forget to include code-server repo URL.
  - https://github.com/cdr/code-server

# Artifact Hub annonations
# ref: https://artifacthub.io/docs/topics/annotations/helm/
annonations:
  # Once released, remove existing content and write anew
  # changelog before bumping version and tag. This will be
  # used for the chart's page at Artifact Hub.
  artifacthub.io/changes: |
    - kind: added
      description: Update docs, especially the Chart README
    - kind: added
      description: Add .github/FUNDING.yml for the Sponsor button
    - kind: changed
      description: Update .env.example file for Docker-based and Docker Compose instances
    - kind: added
      description: Add Artifact Hub annonations for the web UI

  artifacthub.io/images: |
    # Update image names to point into your own images instead for image security scanning.
    - name: Canonical GHCR image
      image: ghcr.io/code-server-boilerplates/starter-pack
    - name: Canonical Red Hat Quay Container Registry image
      image: quay.io/code-server-boilerplates/starter-pack

  # For the email address, make sure you use the same email
  # on your artifacthub.io account.
  artifacthub.io/maintainers: |
    - name: Andrei Jiroh Halili
      email: andreijiroh@madebythepins.tk

  # Must match the LICENSE file at root directory of the repi.
  artifacthub.io/license: MIT

  artifacthub.io/links: |
    - name: code-server Changelog
      url: https://github.com/cdr/code-server/releases
    - name: Chart Changelog
      # Update this link to use your repository's Releases page.
      url: https://github.com/code-server-boilerplates/starter-pack/releases
    - name: Ask questions on GitHub
      url: https://github.com/code-server-boilerplates/community/discussions
