#!/bin/bash

if [[ $(git config --global gpg.program) != "" ]]; then
  GNUPG_PATH="$(git config --global gpg.program)"
else
  GNUPG_PATH=$(which gpg)
fi
export GNUPG_PATH

function gpg() {
  command "$GNUPG_PATH" "$@"
}

function gpg2() {
  command "$GNUPG_PATH" "$@"
}
