#!/bin/bash


debugLog() {
  if [[ $GH_ACTIONS_MODE != "" ]]; then
    [ "$DEBUG" != "" ] && echo "::debug::$1"
  else
    [ "$DEBUG" != "" ] && echo "debug: $1"
  fi
}

errorLog() {
  if [[ $GH_ACTIONS_MODE == "" ]]; then
    echo "error: $1"
  else
    echo "::error::$1"
  fi
}

warn() {
  if [[ $GH_ACTIONS_MODE == "" ]]; then
    echo "warning: $1"
  else
    echo "::warning ::$1"
  fi
}

JQ_PATH="$(which jq)"

if [[ $JQ_PATH == "" ]]; then
  errorLog "jq not found in PATH. Please install jq on your system to continue." && exit 1
fi

PACKAGE_INDEX_FILE="${PWD}/index/${1}.json"

if [[ ! -d $PACKAGE_INDEX_FILE ]]; then
  errorLog "That chart doesn't exist on our index. Please file a new issue or send us an PR to add that into our charts index. Learn more at https://cdrs-docs.rtapp.tk/charts-index" && exit 1
fi

CLONE_DIR="${PWD}/tmp/$(jq -r .name < ${PACKAGE_INDEX_FILE})"
CHART_NAME="$(jq -r .name < ${PACKAGE_INDEX_FILE})"
GIT_REPO_URL="$(jq -r .repoUrl < ${PACKAGE_INDEX_FILE})"
GIT_REPO_BRANCH="$(jq -r .repoBranch < ${PACKAGE_INDEX_FILE})"
SRC_CHARTS_DIRECTORY="${CLONE_DIR}/$(jq -r .chartsDir < ${PACKAGE_INDEX_FILE})"

debugLog "============== CONFIGURATION DEBUGGER ============"
debugLog "Clone directory: $CLONE_DIR"
debugLog "Git repo: $GIT_REPO_URL"
debugLog "Git branch: $GIT_REPO_BRANCH"
debugLog "Source Helm Charts directory: $SRC_CHARTS_DIRECTORY"
debugLog "=================================================="

debugLog "Cloning $GIT_REPO_URL#$GIT_REPO_BRANCH into $CLONE_DIR"
mkdir ./tmp
git clone --progress --quiet --branch $GIT_REPO_BRANCH $GIT_REPO_URL $CLONE_DIR

debugLog "Copying source chart to this repo's charts"
rm -rv "./charts/$CHART_NAME"
cp "$SRC_CHARTS_DIRECTORY" "./charts/$CHART_NAME"

debugLog "Commiting changes and pushing to GitHub..."
if [[ -z $(git status -s -uall) ]]; then
  git add charts/
  git commit --gpg-sign -m "chore(helm-charts): Update package repo index and update charts" --signoff
  git push origin
else
  warn "No changes detected."
fi
