#!/bin/bash

debugLog() {
  if [[ $GH_ACTIONS_MODE != "" ]]; then
    echo "::debug::$1"
  else
    [ "$DEBUG" != "" ] && echo "debug: $1"
  fi
}

errorLog() {
  if [[ $GH_ACTIONS_MODE == "" ]]; then
    echo "error: $1"
  else
    echo "::error::$1"
  fi
}

warn() {
  if [[ $GH_ACTIONS_MODE == "" ]]; then
    echo "warning: $1"
  else
    echo "::warning ::$1"
  fi
}

JQ_PATH="$(which jq)"

if [[ $JQ_PATH == "" ]]; then
  errorLog "jq not found in PATH. Please install jq on your system to continue." && exit 1
fi

if ./scripts/check-if-manifest-exists "$1"; then
  debugLog "Everything is fine"
else
  errorLog "Is that index file ever exists?"
fi

PACKAGE_INDEX_FILE="${PWD}/index/${1}.json"
CLONE_DIR="${PWD}/tmp/$(jq -r .name < ${PACKAGE_INDEX_FILE})"
CHART_NAME="$(jq -r .name < ${PACKAGE_INDEX_FILE})"
GIT_REPO_URL="$(jq -r .repoUrl < ${PACKAGE_INDEX_FILE})"
GIT_REPO_BRANCH="$(jq -r .repoBranch < ${PACKAGE_INDEX_FILE})"
SRC_CHARTS_DIRECTORY="${CLONE_DIR}/$(jq -r .chartsDir < ${PACKAGE_INDEX_FILE})"

debugLog "============== CONFIGURATION DEBUGGER ============"
debugLog "Clone directory: $CLONE_DIR"
debugLog "Git repo: $GIT_REPO_URL"
debugLog "Git branch: $GIT_REPO_BRANCH"
debugLog "Source Helm Charts directory: $SRC_CHARTS_DIRECTORY"
debugLog "=================================================="

debugLog "Cloning $GIT_REPO_URL#$GIT_REPO_BRANCH into $CLONE_DIR"
mkdir ./tmp
git clone --progress --quiet --branch $GIT_REPO_BRANCH $GIT_REPO_URL $CLONE_DIR

debugLog "Copying source chart to this repo's charts"
if [ ! -d "./charts/$CHARTS_NAME" ]; then
  rm -rv "./charts/$CHART_NAME"
else
  warn "Looks like new chart is about to be added. In case of renames, make sure to increment the chart version at either minor or patch number and enable deprecation flag with reason as per https://cdrs-docs.rtapp.tk/renamed-charts."
fi
cp -r "$SRC_CHARTS_DIRECTORY" "./charts/$CHART_NAME"

debugLog "Commiting changes and pushing to GitHub..."
debugLog "$(git status -s uall)"
if [[ -z $(git status -s -uall) ]] && [[ $NO_PUSH != "" ]]; then
  git add charts/
  git commit --gpg-sign -m "chore(helm-charts): Update package repo index and update charts" --signoff
  git push origin
else
  warn "No changes detected. (We didn't echo out this error as an error to prevent false positives and the flood of error notifications in Discord and Guilded. If the problem arises during the job, please check the chart's manifest file here and in source chart repo for any mismatches.)"
fi
