#!/bin/bash

JQ_PATH="$(which jq)"

if [[ $JQ_PATH == "" ]]; then
  echo "error: jq not found in PATH. Please install jq on your system"
  echo "error: to continue. Exiting..."
fi

PACKAGE_INDEX_FILE="${PWD}/index/${1}.json"

if [[ ! -d $PACKAGE_INDEX_FILE ]]; then
  echo "error: That chart doesn't exist on our index. Please file a new issue"
  echo "error: or send us an PR to add that into our charts index."
  echo "error: Learn more at https://cdrs-docs.rtapp.tk/charts-index"
  exit 1
fi

CLONE_DIR="${PWD}/$(jq -r .name < ${PACKAGE_INDEX_FILE})"
CHART_NAME="$(jq -r .name < ${PACKAGE_INDEX_FILE})"
GIT_REPO_URL="$(jq -r .repoUrl < ${PACKAGE_INDEX_FILE})"
GIT_REPO_BRANCH="$(jq -r .repoBranch < ${PACKAGE_INDEX_FILE})"
SRC_CHARTS_DIRECTORY="${CLONE_DIR}/$(jq -r .chartsDir < ${PACKAGE_INDEX_FILE})"

debugLog() {
  [ "$DEBUG" != "" ] && echo "debug: $1"
}

debugLog "============== CONFIGURATION DEBUGGER ============"
debugLog "Clone directory: $CLONE_DIR"
debugLog "Git repo: $GIT_REPO_URL"
debugLog "Git branch: $GIT_REPO_BRANCH"
debugLog "Source Helm Charts directory: $SRC_CHARTS_DIRECTORY"
debugLog "=================================================="

debugLog "Cloning $GIT_REPO_URL#$GIT_REPO_BRANCH into $CLONE_DIR"
git clone --progress --quiet --branch $GIT_REPO_BRANCH $GIT_REPO_URL $CLONE_DIR

debugLog "Copying source chart to this repo's charts"
rm -rv "./charts/$CHART_NAME"
cp -R "$SRC_CHARTS_DIRECTORY" "./$CHART_NAME"

debugLog "Commiting changes and pushing to GitHub..."
git add .
git commit --gpg-sign -m "chore(helm-charts): Update package repo index and update charts" --signoff
git push origin
